name: Sync specific folders and files

on:
  schedule:
    - cron: '30 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository (rime-ice)
        uses: actions/checkout@v4
        with:
          repository: "iDvel/rime-ice"
          token: ${{ secrets.TOKEN_FOR_SQUIRREL }}
          path: "ice"

      - name: Checkout source repository (rime-frost)
        uses: actions/checkout@v4
        with:
          repository: "gaboolic/rime-frost"
          token: ${{ secrets.TOKEN_FOR_SQUIRREL }}
          path: "frost"

      - name: Checkout destination repository
        uses: actions/checkout@v4
        with:
          repository: "qvshuo/squirrel"
          token: ${{ secrets.TOKEN_FOR_SQUIRREL }}
          path: "target"

      - name: Sync folders and files from rime-ice
        run: |
          rsync -av ice/melt_eng.dict.yaml target/
          rsync -av ice/en_dicts/en.dict.yaml target/en_dicts/
          rsync -av ice/en_dicts/en_ext.dict.yaml target/en_dicts/
          rsync -av ice/lua/reduce_english_filter.lua target/lua/

      - name: Sync cn_dicts_cell from rime-frost
        run: |
          rsync -av frost/cn_dicts/8105.dict.yaml target/cn_dicts/
          rsync -av frost/cn_dicts/41448.dict.yaml target/cn_dicts/
          rsync -av frost/cn_dicts/base.dict.yaml target/cn_dicts/
          rsync -av frost/cn_dicts/ext.dict.yaml target/cn_dicts/
          rsync -av frost/cn_dicts/others.dict.yaml target/cn_dicts/
          rsync -av frost/cn_dicts_cell/ target/cn_dicts_cell/

      - name: Sync yuanshen dictionary
        run: |
          curl -L -o target/cn_dicts/yuanshen.dict.yaml https://github.com/qvshuo/rime-pinyin-yuanshen/releases/download/latest/rime-pinyin-yuanshen.dict.yaml

      - name: Push changes
        run: |
          cd target
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync specific folders and files"
            git push
          fi
