name: Sync specific folders and files

on:
  schedule:
    - cron: "30 0 * * 0"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: "iDvel/rime-ice"
          token: ${{ secrets.TOKEN_FOR_SQUIRREL }}
          path: "ice"

      - name: Checkout source repository (rime-frost)
        uses: actions/checkout@v3
        with:
          repository: "gaboolic/rime-frost"
          token: ${{ secrets.TOKEN_FOR_SQUIRREL }}
          path: "frost"

      - name: Checkout destination repository
        uses: actions/checkout@v3
        with:
          repository: "qvshuo/squirrel"
          token: ${{ secrets.TOKEN_FOR_SQUIRREL }}
          path: "target"

      - name: Sync folders and files from rime-ice
        run: |
          rsync -a ice/melt_eng.dict.yaml target/
          rsync -a ice/en_dicts/en.dict.yaml target/en_dicts/
          rsync -a ice/en_dicts/en_ext.dict.yaml target/en_dicts/
          rsync -a ice/lua/reduce_english_filter.lua target/lua/

      - name: Sync cn_dicts_cell from rime-frost
        run: |
          rsync -a frost/cn_dicts/8105.dict.yaml target/cn_dicts/
          rsync -a frost/cn_dicts/41448.dict.yaml target/cn_dicts/
          rsync -a frost/cn_dicts/base.dict.yaml target/cn_dicts/
          rsync -a frost/cn_dicts/ext.dict.yaml target/cn_dicts/
          rsync -a frost/cn_dicts/others.dict.yaml target/cn_dicts/
          rsync -a frost/cn_dicts_cell/ target/cn_dicts_cell/

      - name: Push changes
        run: |
          cd target
          git config user.name 'qvshuo'
          git config user.email 'qvshuo@foxmail.com'
          git add .
          git commit -m 'Sync specific folders and files' || echo "No changes to commit"
          git push
