name: Sync dictionaries and lua scripts

on:
  schedule:
    - cron: '30 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository (rime-ice)
        uses: actions/checkout@v6
        with:
          repository: "iDvel/rime-ice"
          path: "ice"

      - name: Checkout source repository (rime-frost)
        uses: actions/checkout@v6
        with:
          repository: "gaboolic/rime-frost"
          ref: "master"
          path: "frost"

      - name: Checkout destination repository
        uses: actions/checkout@v6
        with:
          path: "target"

      - name: Sync dictionaries and lua scripts from rime-ice
        run: |
          rsync -av ice/melt_eng.dict.yaml target/
          rsync -av ice/en_dicts/en.dict.yaml target/en_dicts/
          rsync -av ice/en_dicts/en_ext.dict.yaml target/en_dicts/
          rsync -av ice/lua/reduce_english_filter.lua target/lua/

      - name: Sync rime-frost main dictionaries
        run: |
          rsync -av \
            frost/cn_dicts/8105.dict.yaml \
            frost/cn_dicts/41448.dict.yaml \
            frost/cn_dicts/base.dict.yaml \
            frost/cn_dicts/ext.dict.yaml \
            frost/cn_dicts/tencent.dict.yaml \
            frost/cn_dicts/others.dict.yaml \
            frost/cn_dicts_cell/composite.dict.yaml \
            target/cn_dicts/

      - name: Sync Yuanshen dictionary
        run: |
          curl -L -o target/cn_dicts/yuanshen.dict.yaml https://github.com/qvshuo/rime-luna-pinyin-custom-dict/releases/download/yuanshen/yuanshen.dict.yaml

      - name: Sync Sogou Internet Buzzwords dictionary
        run: |
          curl -L -o target/cn_dicts/buzzwords.dict.yaml https://github.com/qvshuo/rime-luna-pinyin-custom-dict/releases/download/buzzwords/buzzwords.dict.yaml

      - name: Push changes
        run: |
          cd target
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync dictionaries and lua scripts."
            git push
          fi
