name: Sync dictionaries and lua scripts

on:
  schedule:
    - cron: '30 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository (rime-ice)
        uses: actions/checkout@v4
        with:
          repository: "iDvel/rime-ice"
          path: "ice"

      - name: Checkout source repository (RIME-LMDG)
        uses: actions/checkout@v4
        with:
          repository: "amzxyz/RIME-LMDG"
          ref: "wanxiang"
          path: "lmdg"

      - name: Checkout destination repository
        uses: actions/checkout@v4
        with:
          repository: "qvshuo/squirrel"
          token: ${{ secrets.TOKEN_FOR_SQUIRREL }}
          path: "target"

      - name: Sync dictionaries and lua scripts from rime-ice
        run: |
          rsync -av ice/melt_eng.dict.yaml target/
          rsync -av ice/en_dicts/en.dict.yaml target/en_dicts/
          rsync -av ice/en_dicts/en_ext.dict.yaml target/en_dicts/
          rsync -av ice/lua/reduce_english_filter.lua target/lua/

      - name: Process and Sync LMDG dictionaries
        run: |
          for file in lmdg/dicts/*.yaml; do
            echo "Processing $file"
            sed -i \
              -e 's/ā/a/g' \
              -e 's/á/a/g' \
              -e 's/ǎ/a/g' \
              -e 's/à/a/g' \
              -e 's/ō/o/g' \
              -e 's/ó/o/g' \
              -e 's/ǒ/o/g' \
              -e 's/ò/o/g' \
              -e 's/ē/e/g' \
              -e 's/é/e/g' \
              -e 's/ě/e/g' \
              -e 's/è/e/g' \
              -e 's/ī/i/g' \
              -e 's/í/i/g' \
              -e 's/ǐ/i/g' \
              -e 's/ì/i/g' \
              -e 's/ū/u/g' \
              -e 's/ú/u/g' \
              -e 's/ǔ/u/g' \
              -e 's/ù/u/g' \
              -e 's/ǖ/v/g' \
              -e 's/ǘ/v/g' \
              -e 's/ǚ/v/g' \
              -e 's/ǜ/v/g' \
              -e 's/ü/v/g' \
              "$file"
          done

          rsync -av lmdg/dicts/*.yaml target/cn_dicts/

      - name: Sync Yuanshen dictionary
        run: |
          curl -L -o target/cn_dicts/yuanshen.dict.yaml https://github.com/qvshuo/rime-luna-pinyin-custom-dict/releases/download/yuanshen/yuanshen.dict.yaml

      - name: Sync Sogou Internet Buzzwords dictionary
        run: |
          curl -L -o target/cn_dicts/buzzwords.dict.yaml https://github.com/qvshuo/rime-luna-pinyin-custom-dict/releases/download/buzzwords/buzzwords.dict.yaml

      - name: Push changes
        run: |
          cd target
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync dictionaries and lua scripts."
            git push
          fi
